apiVersion: apps/v1
kind: Deployment
metadata:
  name: viet-deployment
  namespace: viet-capstone
  labels:
    app: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: webserver
          image: 399684875495.dkr.ecr.us-east-1.amazonaws.com/vietcapstone:latest
          ports:
            - containerPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%

---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer
  namespace: viet-capstone
spec:
  selector:
    app: webserver
  type: LoadBalancer
  ports:
    - port: 80
