apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: udacity-capstore
  region: us-east-1
  version: '1.27'

availabilityZones: ["us-east-1a", "us-east-1b"]

nodeGroups:
  - name: udacity-nodegroup
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    volumeSize: 20